# Generated by Django 2.0.2 on 2018-03-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='times',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tag',
            name='times',
            field=models.IntegerField(default=1),
        ),
    ]
