# Generated by Django 2.0.2 on 2018-03-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180303_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='times',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='times',
        ),
    ]
